window-dragging=no
# do not show timeline when
osd-on-seek=no

# prefer japanese audio when available
alang=jpn,ja
# prefer english subtitles when available
slang=eng,en

# subtitles vertical position
sub-pos=100
# enable secondary subtitles (may be separate for songs & subs)
secondary-sid=auto
secondary-sub-pos=105

# remember settings & watch time
save-position-on-quit=yes
