#! /bin/sh

session_name="my_session_$(date +"%Y%m%d_%H%M%S")"

tnux new-session -d -s "$session_name"
tmux rename-window -t "$session_name:1" 'code'
tmux new-window -t "$session_name" -d -n 'term'
tmux attach-session -t "$session_name"
