[terminal.shell]
program = "/bin/zsh"

[debug]
prefer_egl = true

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.normal]
style = "Regular"

# short and thick
family = "CaskaydiaMono Nerd Font"

# basic, a bit hard on the eyes
#family = "DejaVuSansM Nerd Font"

# thinner and taller than caskaydia, and not as round
#family = "JetbrainsMono Nerd Font"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]
