[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "DejaVu Sans Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]
